---
name: Stage

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Create an early-access release
    environment: staging

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Create release notes from changelog
        id: release-notes
        run: |
          version="v0.9.2"
          version=${version#v}
          notes=$(sed -n "/## $version/,/^##/p" ./CHANGELOG.md | grep -v '##')
          if [ -z "$notes" ]; then
            echo "Release notes are missing for version $version."
            exit 1
          else
            echo "version=$version" >> "$GITHUB_OUTPUT"
            delimiter="$(openssl rand -hex 8)"
            echo "notes<<${delimiter}" >> "$GITHUB_OUTPUT"
            echo "$notes" >> "$GITHUB_OUTPUT"
            echo "${delimiter}" >> "$GITHUB_OUTPUT"
          fi
          
      - name: Update date in CHANGELOG.md
        run: |
          versioncheck="${{ steps.release-notes.outputs.version }}"
          notescheck="${{ steps.release-notes.outputs.notes }}"
          echo $versioncheck
          echo $notescheck
          day_suffix=$(date +"%e" | sed 's/^[[:space:]]*//')   
          if [ "$day_suffix" = "1" ] || [ "$day_suffix" = "21" ] || [ "$day_suffix" = "31" ]; then
            suffix="st"
          elif [ "$day_suffix" = "2" ] || [ "$day_suffix" = "22" ]; then
            suffix="nd"
          elif [ "$day_suffix" = "3" ] || [ "$day_suffix" = "23" ]; then
            suffix="rd"
          else
            suffix="th"
          fi 
          today="$(date +"%b %-d")$suffix $(date +"%Y")"

          version="0.9.1"
          if grep -qE "## $version \([^)]*\)" ./CHANGELOG.md; then
            current_date=$(grep -oP "(?<=## $version \()[^\)]*" ./CHANGELOG.md)
            if [ "$current_date" != "$today" ]; then
              sed -E -i "s/## $version \([^)]*\)/## $version ($today)/" CHANGELOG.md
            fi
          else
            sed -E -i "s/## $version/## $version ($today)/" CHANGELOG.md
          fi

          cat CHANGELOG.md
