---
name: Stage

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Create an early-access release
    environment: staging

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Update date in CHANGELOG.md
        run: |
          day_suffix=23
          if [ "$day_suffix" = "1" ] || [ "$day_suffix" = "21" ] || [ "$day_suffix" = "31" ]; then
            suffix="st"
          elif [ "$day_suffix" = "2" ] || [ "$day_suffix" = "22" ]; then
            suffix="nd"
          elif [ "$day_suffix" = "3" ] || [ "$day_suffix" = "23" ]; then
            suffix="rd"
          else
            suffix="th"
          fi 
          today="$(date +"%b %-d")$suffix $(date +"%Y")"

          version="0.9.1"
          current_date=$(grep -oP "(?<=## $version \()[^\)]+" ./CHANGELOG.md)

          if [ "$current_date" != "$today" ]; then
            sed -E -i "s/## $version \([^)]*\)/## $version ($today)/" CHANGELOG.md
          fi

          cat CHANGELOG.md
